-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 17:39:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema samples
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema samples
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `samples` DEFAULT CHARACTER SET utf8 ;
USE `samples` ;

-- -----------------------------------------------------
-- Table `samples`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samples`.`data` (
  `ID` INT NOT NULL,
  `time` TIME NOT NULL DEFAULT 00:00:00,
  `ph` FLOAT NOT NULL,
  `ec` FLOAT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
